import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { socialLinks, SocialLink } from "../utils/social-links";
import { portfolioItems, PortfolioItem } from "../utils/portfolio";

function SocialLinks({ socials }) {
  return (
    <ul className={styles.socialLinks}>
      {socials.map((social: SocialLink) => {
        return (
          <li key={social.id}>
            <a
              target="_blank"
              rel="noreferrer"
              href={social.url}
              id={styles[social.id]}
            >
              <FontAwesomeIcon icon={social.icon} />
              <span className="sr-only">{social.name}</span>
            </a>
          </li>
        );
      })}
    </ul>
  );
}

function AboutMe() {
  return (
    <div className={styles.aboutMe}>
      <Image
        src="/assets/images/photo.jpg"
        alt="Jason Nolfi"
        width={170}
        height={170}
      />
      <h1>Jason Nolfi</h1>
      <p>Midwesterner living in 🌵 Austin, Texas</p>
      <p>
        Frontend Engineer with over a decade of experience crafting clean,
        accessible and performant user experiences for the Web.
      </p>
      <p>Music Nerd. Coffee lover. Always in motion.</p>
      <SocialLinks socials={socialLinks} />
    </div>
  );
}

function Portfolio({ items }) {
  return (
    <section className={styles.portfolio}>
      <h2>Open Source Portfolio</h2>
      <div className={styles.grid}>
        {items.map((item: PortfolioItem) => {
          return (
            <div className={styles.card} key={item.id}>
              <a
                className={styles.workItem}
                href={item.url}
                target="_blank"
                rel="noreferrer"
              >
                <div className={styles.workImg} id={styles[item.id]}></div>
                <div className={styles.workInfo}>
                  <h3>{item.title}</h3>
                  <p>{item.subtitle}</p>
                  <ul>
                    {item.tags.map((tag) => (
                      <li key={tag}>{tag}</li>
                    ))}
                  </ul>
                </div>
              </a>
            </div>
          );
        })}
      </div>
    </section>
  );
}
function Footer() {
  function getYear() {
    const date = new Date();
    const year = date.getFullYear();
    return year;
  }
  return (
    <footer className={styles.footer}>
      © {getYear()} <span>Jason Nolfi</span>
    </footer>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Jason Nolfi | Web Developer | Austin, TX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AboutMe />
        <Portfolio items={portfolioItems} />
      </main>

      <Footer />
    </>
  );
}
