import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { portfolioItems } from "../utils/portfolio";
import { Portfolio } from "../components/portfolio";
import { AboutMe } from "../components/about-me";
import { Footer } from "../components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jason Nolfi | Web Developer | Austin, TX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AboutMe />
        <Portfolio items={portfolioItems} />
      </main>

      <Footer />
    </>
  );
}
